server:
  port: 8089
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8088"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/**
          filters:
            - AuthenticationFilter
        - id: post-service
          uri: lb://post-service
          predicates:
            - Path=/api/**
          filters:
            - AuthenticationFilter

        - id: like-service
          uri: lb://like-service
          predicates:
            - Path=/api/**
          filters:
            - AuthenticationFilter

        - id: comment-service
          uri: lb://comment-service
          predicates:
            - Path=/api/**
          filters:
            - AuthenticationFilter

        - id: friend-service
          uri: lb://friend-service
          predicates:
            - Path=/api/**
          filters:
            - AuthenticationFilter

        - id: identity-service
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Path=/auth/**